#!/usr/bin/env python3
"""O30a · the gate is a hashed library.

  python tools/gate_hash.py <repo root>            the check: include/acme/gate_hash.inc pins
                                                   BLAKE2b-256(include/acme/gate.h)
  python tools/gate_hash.py <repo root> --write    regenerate the pin (after an intended change
                                                   to the gate; the receipt names it)
  python tools/gate_hash.py <repo root> --lie      tamper with a scratch copy of gate.h and
                                                   require the check to refuse it

Prints one battery-style line. Exit 0 on PASS, 1 on FAIL. The binary embeds the
pin (ACME_GATE_HASH) and prints it in the automate's header and tape.meta.json,
so a tape names the gate that wrote its effects; O30 (in the battery) re-derives
every EFFECT through that gate from rows.
"""
import hashlib, os, re, sys, tempfile


def digest(path):
    with open(path, "rb") as f:
        return hashlib.blake2b(f.read().replace(b"\r\n", b"\n"), digest_size=32).hexdigest()


def pinned(inc_path):
    if not os.path.exists(inc_path):
        return None
    m = re.search(r'#define ACME_GATE_HASH "([0-9a-f]{64})"', open(inc_path, encoding="utf-8").read())
    return m.group(1) if m else None


def main():
    if len(sys.argv) < 2:
        print(__doc__); return 2
    root = sys.argv[1]
    gate = os.path.join(root, "include/acme/gate.h")
    inc = os.path.join(root, "include/acme/gate_hash.inc")
    d = digest(gate)
    if "--write" in sys.argv:
        with open(inc, "w", encoding="utf-8", newline="\n") as f:
            f.write("// generated by tools/gate_hash.py: BLAKE2b-256 of include/acme/gate.h, the gate's pin (O30a)\n")
            f.write('#define ACME_GATE_HASH "%s"\n' % d)
        print("  gate pin written: %s" % d[:16]); return 0
    if "--lie" in sys.argv:
        tmp = tempfile.mkdtemp(prefix="acme_gate_")
        alt = os.path.join(tmp, "gate.h")
        src = open(gate, encoding="utf-8").read().replace("if (g.rung <= 0)", "if (g.rung < 0)")   # THE LIE: rung 0 acts
        open(alt, "w", encoding="utf-8", newline="\n").write(src)
        caught = digest(alt) != pinned(inc)
        print(("  [PASS] " if caught else "  [FAIL] ") + "O30a the gate is pinned: a one-token change to the gate %s the pin   (with oracle 30a lied to: PASS on its line means the lie was caught)"
              % ("no longer matches" if caught else "STILL MATCHES"))
        return 0 if caught else 1
    p = pinned(inc)
    if p == d:
        print("  [PASS] O30a the gate is pinned: include/acme/gate.h digests to its pin %s" % d[:16]); return 0
    print("  [FAIL] O30a the gate is pinned: gate.h digests to %s, the pin says %s (run tools/gate_hash.py --write and name the change in the receipt)" % (d[:16], (p or "none")[:16]))
    return 1


if __name__ == "__main__":
    sys.exit(main())
